name: app_banhang2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.7
  http: ^1.2.2
  provider: ^6.0.0
  loading_animation_widget: ^1.3.0
  flutter_spinkit: ^5.2.1
  carousel_slider: ^5.0.0
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/intro.png
    - assets/images/apple.png
    - assets/images/google.png
    - assets/images/home.png
    - assets/images/order.png
    - assets/images/profile.png
    - assets/images/acces1.png
    - assets/images/beauty.png
    - assets/images/men.png
    - assets/images/men1.png
    - assets/images/women1.png
    - assets/images/banner.png
    - assets/images/banner1.jpg
    - assets/images/banner2.jpg
    - assets/images/banner3.png
    - assets/images/banner4.png
    - assets/images/avatar.png
    - assets/images/shirt1.png
    - assets/images/shirt2.png
    - assets/images/shirt3.png
    - assets/images/accessories.png
    - assets/images/clothing.png
    - assets/images/collection.png
    - assets/images/shoes.png
    - assets/images/Ticket.png
    - assets/images/support.png
    - assets/images/clothes.png